# permissions for end users to view certengines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certengine-viewer-role
rules:
- apiGroups:
  - certengine.certengine.kubebuilder.domain
  resources:
  - certengines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - certengine.certengine.kubebuilder.domain
  resources:
  - certengines/status
  verbs:
  - get
